//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	oauthv1 "github.com/openshift/api/oauth/v1"
	oauth "github.com/openshift/oauth-apiserver/pkg/oauth/apis/oauth"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*oauthv1.ClusterRoleScopeRestriction)(nil), (*oauth.ClusterRoleScopeRestriction)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterRoleScopeRestriction_To_oauth_ClusterRoleScopeRestriction(a.(*oauthv1.ClusterRoleScopeRestriction), b.(*oauth.ClusterRoleScopeRestriction), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauth.ClusterRoleScopeRestriction)(nil), (*oauthv1.ClusterRoleScopeRestriction)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_oauth_ClusterRoleScopeRestriction_To_v1_ClusterRoleScopeRestriction(a.(*oauth.ClusterRoleScopeRestriction), b.(*oauthv1.ClusterRoleScopeRestriction), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauthv1.OAuthAccessToken)(nil), (*oauth.OAuthAccessToken)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OAuthAccessToken_To_oauth_OAuthAccessToken(a.(*oauthv1.OAuthAccessToken), b.(*oauth.OAuthAccessToken), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauth.OAuthAccessToken)(nil), (*oauthv1.OAuthAccessToken)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_oauth_OAuthAccessToken_To_v1_OAuthAccessToken(a.(*oauth.OAuthAccessToken), b.(*oauthv1.OAuthAccessToken), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauthv1.OAuthAccessTokenList)(nil), (*oauth.OAuthAccessTokenList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OAuthAccessTokenList_To_oauth_OAuthAccessTokenList(a.(*oauthv1.OAuthAccessTokenList), b.(*oauth.OAuthAccessTokenList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauth.OAuthAccessTokenList)(nil), (*oauthv1.OAuthAccessTokenList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_oauth_OAuthAccessTokenList_To_v1_OAuthAccessTokenList(a.(*oauth.OAuthAccessTokenList), b.(*oauthv1.OAuthAccessTokenList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauthv1.OAuthAuthorizeToken)(nil), (*oauth.OAuthAuthorizeToken)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OAuthAuthorizeToken_To_oauth_OAuthAuthorizeToken(a.(*oauthv1.OAuthAuthorizeToken), b.(*oauth.OAuthAuthorizeToken), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauth.OAuthAuthorizeToken)(nil), (*oauthv1.OAuthAuthorizeToken)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_oauth_OAuthAuthorizeToken_To_v1_OAuthAuthorizeToken(a.(*oauth.OAuthAuthorizeToken), b.(*oauthv1.OAuthAuthorizeToken), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauthv1.OAuthAuthorizeTokenList)(nil), (*oauth.OAuthAuthorizeTokenList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OAuthAuthorizeTokenList_To_oauth_OAuthAuthorizeTokenList(a.(*oauthv1.OAuthAuthorizeTokenList), b.(*oauth.OAuthAuthorizeTokenList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauth.OAuthAuthorizeTokenList)(nil), (*oauthv1.OAuthAuthorizeTokenList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_oauth_OAuthAuthorizeTokenList_To_v1_OAuthAuthorizeTokenList(a.(*oauth.OAuthAuthorizeTokenList), b.(*oauthv1.OAuthAuthorizeTokenList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauthv1.OAuthClient)(nil), (*oauth.OAuthClient)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OAuthClient_To_oauth_OAuthClient(a.(*oauthv1.OAuthClient), b.(*oauth.OAuthClient), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauth.OAuthClient)(nil), (*oauthv1.OAuthClient)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_oauth_OAuthClient_To_v1_OAuthClient(a.(*oauth.OAuthClient), b.(*oauthv1.OAuthClient), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauthv1.OAuthClientAuthorization)(nil), (*oauth.OAuthClientAuthorization)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OAuthClientAuthorization_To_oauth_OAuthClientAuthorization(a.(*oauthv1.OAuthClientAuthorization), b.(*oauth.OAuthClientAuthorization), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauth.OAuthClientAuthorization)(nil), (*oauthv1.OAuthClientAuthorization)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_oauth_OAuthClientAuthorization_To_v1_OAuthClientAuthorization(a.(*oauth.OAuthClientAuthorization), b.(*oauthv1.OAuthClientAuthorization), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauthv1.OAuthClientAuthorizationList)(nil), (*oauth.OAuthClientAuthorizationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OAuthClientAuthorizationList_To_oauth_OAuthClientAuthorizationList(a.(*oauthv1.OAuthClientAuthorizationList), b.(*oauth.OAuthClientAuthorizationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauth.OAuthClientAuthorizationList)(nil), (*oauthv1.OAuthClientAuthorizationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_oauth_OAuthClientAuthorizationList_To_v1_OAuthClientAuthorizationList(a.(*oauth.OAuthClientAuthorizationList), b.(*oauthv1.OAuthClientAuthorizationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauthv1.OAuthClientList)(nil), (*oauth.OAuthClientList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OAuthClientList_To_oauth_OAuthClientList(a.(*oauthv1.OAuthClientList), b.(*oauth.OAuthClientList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauth.OAuthClientList)(nil), (*oauthv1.OAuthClientList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_oauth_OAuthClientList_To_v1_OAuthClientList(a.(*oauth.OAuthClientList), b.(*oauthv1.OAuthClientList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauthv1.OAuthRedirectReference)(nil), (*oauth.OAuthRedirectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_OAuthRedirectReference_To_oauth_OAuthRedirectReference(a.(*oauthv1.OAuthRedirectReference), b.(*oauth.OAuthRedirectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauth.OAuthRedirectReference)(nil), (*oauthv1.OAuthRedirectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_oauth_OAuthRedirectReference_To_v1_OAuthRedirectReference(a.(*oauth.OAuthRedirectReference), b.(*oauthv1.OAuthRedirectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauthv1.RedirectReference)(nil), (*oauth.RedirectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RedirectReference_To_oauth_RedirectReference(a.(*oauthv1.RedirectReference), b.(*oauth.RedirectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauth.RedirectReference)(nil), (*oauthv1.RedirectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_oauth_RedirectReference_To_v1_RedirectReference(a.(*oauth.RedirectReference), b.(*oauthv1.RedirectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauthv1.ScopeRestriction)(nil), (*oauth.ScopeRestriction)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ScopeRestriction_To_oauth_ScopeRestriction(a.(*oauthv1.ScopeRestriction), b.(*oauth.ScopeRestriction), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauth.ScopeRestriction)(nil), (*oauthv1.ScopeRestriction)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_oauth_ScopeRestriction_To_v1_ScopeRestriction(a.(*oauth.ScopeRestriction), b.(*oauthv1.ScopeRestriction), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauthv1.UserOAuthAccessToken)(nil), (*oauth.UserOAuthAccessToken)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_UserOAuthAccessToken_To_oauth_UserOAuthAccessToken(a.(*oauthv1.UserOAuthAccessToken), b.(*oauth.UserOAuthAccessToken), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauth.UserOAuthAccessToken)(nil), (*oauthv1.UserOAuthAccessToken)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_oauth_UserOAuthAccessToken_To_v1_UserOAuthAccessToken(a.(*oauth.UserOAuthAccessToken), b.(*oauthv1.UserOAuthAccessToken), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauthv1.UserOAuthAccessTokenList)(nil), (*oauth.UserOAuthAccessTokenList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_UserOAuthAccessTokenList_To_oauth_UserOAuthAccessTokenList(a.(*oauthv1.UserOAuthAccessTokenList), b.(*oauth.UserOAuthAccessTokenList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*oauth.UserOAuthAccessTokenList)(nil), (*oauthv1.UserOAuthAccessTokenList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_oauth_UserOAuthAccessTokenList_To_v1_UserOAuthAccessTokenList(a.(*oauth.UserOAuthAccessTokenList), b.(*oauthv1.UserOAuthAccessTokenList), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_ClusterRoleScopeRestriction_To_oauth_ClusterRoleScopeRestriction(in *oauthv1.ClusterRoleScopeRestriction, out *oauth.ClusterRoleScopeRestriction, s conversion.Scope) error {
	out.RoleNames = *(*[]string)(unsafe.Pointer(&in.RoleNames))
	out.Namespaces = *(*[]string)(unsafe.Pointer(&in.Namespaces))
	out.AllowEscalation = in.AllowEscalation
	return nil
}

// Convert_v1_ClusterRoleScopeRestriction_To_oauth_ClusterRoleScopeRestriction is an autogenerated conversion function.
func Convert_v1_ClusterRoleScopeRestriction_To_oauth_ClusterRoleScopeRestriction(in *oauthv1.ClusterRoleScopeRestriction, out *oauth.ClusterRoleScopeRestriction, s conversion.Scope) error {
	return autoConvert_v1_ClusterRoleScopeRestriction_To_oauth_ClusterRoleScopeRestriction(in, out, s)
}

func autoConvert_oauth_ClusterRoleScopeRestriction_To_v1_ClusterRoleScopeRestriction(in *oauth.ClusterRoleScopeRestriction, out *oauthv1.ClusterRoleScopeRestriction, s conversion.Scope) error {
	out.RoleNames = *(*[]string)(unsafe.Pointer(&in.RoleNames))
	out.Namespaces = *(*[]string)(unsafe.Pointer(&in.Namespaces))
	out.AllowEscalation = in.AllowEscalation
	return nil
}

// Convert_oauth_ClusterRoleScopeRestriction_To_v1_ClusterRoleScopeRestriction is an autogenerated conversion function.
func Convert_oauth_ClusterRoleScopeRestriction_To_v1_ClusterRoleScopeRestriction(in *oauth.ClusterRoleScopeRestriction, out *oauthv1.ClusterRoleScopeRestriction, s conversion.Scope) error {
	return autoConvert_oauth_ClusterRoleScopeRestriction_To_v1_ClusterRoleScopeRestriction(in, out, s)
}

func autoConvert_v1_OAuthAccessToken_To_oauth_OAuthAccessToken(in *oauthv1.OAuthAccessToken, out *oauth.OAuthAccessToken, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ClientName = in.ClientName
	out.ExpiresIn = in.ExpiresIn
	out.Scopes = *(*[]string)(unsafe.Pointer(&in.Scopes))
	out.RedirectURI = in.RedirectURI
	out.UserName = in.UserName
	out.UserUID = in.UserUID
	out.AuthorizeToken = in.AuthorizeToken
	out.RefreshToken = in.RefreshToken
	out.InactivityTimeoutSeconds = in.InactivityTimeoutSeconds
	return nil
}

// Convert_v1_OAuthAccessToken_To_oauth_OAuthAccessToken is an autogenerated conversion function.
func Convert_v1_OAuthAccessToken_To_oauth_OAuthAccessToken(in *oauthv1.OAuthAccessToken, out *oauth.OAuthAccessToken, s conversion.Scope) error {
	return autoConvert_v1_OAuthAccessToken_To_oauth_OAuthAccessToken(in, out, s)
}

func autoConvert_oauth_OAuthAccessToken_To_v1_OAuthAccessToken(in *oauth.OAuthAccessToken, out *oauthv1.OAuthAccessToken, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ClientName = in.ClientName
	out.ExpiresIn = in.ExpiresIn
	out.Scopes = *(*[]string)(unsafe.Pointer(&in.Scopes))
	out.RedirectURI = in.RedirectURI
	out.UserName = in.UserName
	out.UserUID = in.UserUID
	out.AuthorizeToken = in.AuthorizeToken
	out.RefreshToken = in.RefreshToken
	out.InactivityTimeoutSeconds = in.InactivityTimeoutSeconds
	return nil
}

// Convert_oauth_OAuthAccessToken_To_v1_OAuthAccessToken is an autogenerated conversion function.
func Convert_oauth_OAuthAccessToken_To_v1_OAuthAccessToken(in *oauth.OAuthAccessToken, out *oauthv1.OAuthAccessToken, s conversion.Scope) error {
	return autoConvert_oauth_OAuthAccessToken_To_v1_OAuthAccessToken(in, out, s)
}

func autoConvert_v1_OAuthAccessTokenList_To_oauth_OAuthAccessTokenList(in *oauthv1.OAuthAccessTokenList, out *oauth.OAuthAccessTokenList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]oauth.OAuthAccessToken)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_OAuthAccessTokenList_To_oauth_OAuthAccessTokenList is an autogenerated conversion function.
func Convert_v1_OAuthAccessTokenList_To_oauth_OAuthAccessTokenList(in *oauthv1.OAuthAccessTokenList, out *oauth.OAuthAccessTokenList, s conversion.Scope) error {
	return autoConvert_v1_OAuthAccessTokenList_To_oauth_OAuthAccessTokenList(in, out, s)
}

func autoConvert_oauth_OAuthAccessTokenList_To_v1_OAuthAccessTokenList(in *oauth.OAuthAccessTokenList, out *oauthv1.OAuthAccessTokenList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]oauthv1.OAuthAccessToken)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_oauth_OAuthAccessTokenList_To_v1_OAuthAccessTokenList is an autogenerated conversion function.
func Convert_oauth_OAuthAccessTokenList_To_v1_OAuthAccessTokenList(in *oauth.OAuthAccessTokenList, out *oauthv1.OAuthAccessTokenList, s conversion.Scope) error {
	return autoConvert_oauth_OAuthAccessTokenList_To_v1_OAuthAccessTokenList(in, out, s)
}

func autoConvert_v1_OAuthAuthorizeToken_To_oauth_OAuthAuthorizeToken(in *oauthv1.OAuthAuthorizeToken, out *oauth.OAuthAuthorizeToken, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ClientName = in.ClientName
	out.ExpiresIn = in.ExpiresIn
	out.Scopes = *(*[]string)(unsafe.Pointer(&in.Scopes))
	out.RedirectURI = in.RedirectURI
	out.State = in.State
	out.UserName = in.UserName
	out.UserUID = in.UserUID
	out.CodeChallenge = in.CodeChallenge
	out.CodeChallengeMethod = in.CodeChallengeMethod
	return nil
}

// Convert_v1_OAuthAuthorizeToken_To_oauth_OAuthAuthorizeToken is an autogenerated conversion function.
func Convert_v1_OAuthAuthorizeToken_To_oauth_OAuthAuthorizeToken(in *oauthv1.OAuthAuthorizeToken, out *oauth.OAuthAuthorizeToken, s conversion.Scope) error {
	return autoConvert_v1_OAuthAuthorizeToken_To_oauth_OAuthAuthorizeToken(in, out, s)
}

func autoConvert_oauth_OAuthAuthorizeToken_To_v1_OAuthAuthorizeToken(in *oauth.OAuthAuthorizeToken, out *oauthv1.OAuthAuthorizeToken, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ClientName = in.ClientName
	out.ExpiresIn = in.ExpiresIn
	out.Scopes = *(*[]string)(unsafe.Pointer(&in.Scopes))
	out.RedirectURI = in.RedirectURI
	out.State = in.State
	out.UserName = in.UserName
	out.UserUID = in.UserUID
	out.CodeChallenge = in.CodeChallenge
	out.CodeChallengeMethod = in.CodeChallengeMethod
	return nil
}

// Convert_oauth_OAuthAuthorizeToken_To_v1_OAuthAuthorizeToken is an autogenerated conversion function.
func Convert_oauth_OAuthAuthorizeToken_To_v1_OAuthAuthorizeToken(in *oauth.OAuthAuthorizeToken, out *oauthv1.OAuthAuthorizeToken, s conversion.Scope) error {
	return autoConvert_oauth_OAuthAuthorizeToken_To_v1_OAuthAuthorizeToken(in, out, s)
}

func autoConvert_v1_OAuthAuthorizeTokenList_To_oauth_OAuthAuthorizeTokenList(in *oauthv1.OAuthAuthorizeTokenList, out *oauth.OAuthAuthorizeTokenList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]oauth.OAuthAuthorizeToken)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_OAuthAuthorizeTokenList_To_oauth_OAuthAuthorizeTokenList is an autogenerated conversion function.
func Convert_v1_OAuthAuthorizeTokenList_To_oauth_OAuthAuthorizeTokenList(in *oauthv1.OAuthAuthorizeTokenList, out *oauth.OAuthAuthorizeTokenList, s conversion.Scope) error {
	return autoConvert_v1_OAuthAuthorizeTokenList_To_oauth_OAuthAuthorizeTokenList(in, out, s)
}

func autoConvert_oauth_OAuthAuthorizeTokenList_To_v1_OAuthAuthorizeTokenList(in *oauth.OAuthAuthorizeTokenList, out *oauthv1.OAuthAuthorizeTokenList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]oauthv1.OAuthAuthorizeToken)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_oauth_OAuthAuthorizeTokenList_To_v1_OAuthAuthorizeTokenList is an autogenerated conversion function.
func Convert_oauth_OAuthAuthorizeTokenList_To_v1_OAuthAuthorizeTokenList(in *oauth.OAuthAuthorizeTokenList, out *oauthv1.OAuthAuthorizeTokenList, s conversion.Scope) error {
	return autoConvert_oauth_OAuthAuthorizeTokenList_To_v1_OAuthAuthorizeTokenList(in, out, s)
}

func autoConvert_v1_OAuthClient_To_oauth_OAuthClient(in *oauthv1.OAuthClient, out *oauth.OAuthClient, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Secret = in.Secret
	out.AdditionalSecrets = *(*[]string)(unsafe.Pointer(&in.AdditionalSecrets))
	out.RespondWithChallenges = in.RespondWithChallenges
	out.RedirectURIs = *(*[]string)(unsafe.Pointer(&in.RedirectURIs))
	out.GrantMethod = oauth.GrantHandlerType(in.GrantMethod)
	out.ScopeRestrictions = *(*[]oauth.ScopeRestriction)(unsafe.Pointer(&in.ScopeRestrictions))
	out.AccessTokenMaxAgeSeconds = (*int32)(unsafe.Pointer(in.AccessTokenMaxAgeSeconds))
	out.AccessTokenInactivityTimeoutSeconds = (*int32)(unsafe.Pointer(in.AccessTokenInactivityTimeoutSeconds))
	return nil
}

// Convert_v1_OAuthClient_To_oauth_OAuthClient is an autogenerated conversion function.
func Convert_v1_OAuthClient_To_oauth_OAuthClient(in *oauthv1.OAuthClient, out *oauth.OAuthClient, s conversion.Scope) error {
	return autoConvert_v1_OAuthClient_To_oauth_OAuthClient(in, out, s)
}

func autoConvert_oauth_OAuthClient_To_v1_OAuthClient(in *oauth.OAuthClient, out *oauthv1.OAuthClient, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Secret = in.Secret
	out.AdditionalSecrets = *(*[]string)(unsafe.Pointer(&in.AdditionalSecrets))
	out.RespondWithChallenges = in.RespondWithChallenges
	out.RedirectURIs = *(*[]string)(unsafe.Pointer(&in.RedirectURIs))
	out.GrantMethod = oauthv1.GrantHandlerType(in.GrantMethod)
	out.ScopeRestrictions = *(*[]oauthv1.ScopeRestriction)(unsafe.Pointer(&in.ScopeRestrictions))
	out.AccessTokenMaxAgeSeconds = (*int32)(unsafe.Pointer(in.AccessTokenMaxAgeSeconds))
	out.AccessTokenInactivityTimeoutSeconds = (*int32)(unsafe.Pointer(in.AccessTokenInactivityTimeoutSeconds))
	return nil
}

// Convert_oauth_OAuthClient_To_v1_OAuthClient is an autogenerated conversion function.
func Convert_oauth_OAuthClient_To_v1_OAuthClient(in *oauth.OAuthClient, out *oauthv1.OAuthClient, s conversion.Scope) error {
	return autoConvert_oauth_OAuthClient_To_v1_OAuthClient(in, out, s)
}

func autoConvert_v1_OAuthClientAuthorization_To_oauth_OAuthClientAuthorization(in *oauthv1.OAuthClientAuthorization, out *oauth.OAuthClientAuthorization, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ClientName = in.ClientName
	out.UserName = in.UserName
	out.UserUID = in.UserUID
	out.Scopes = *(*[]string)(unsafe.Pointer(&in.Scopes))
	return nil
}

// Convert_v1_OAuthClientAuthorization_To_oauth_OAuthClientAuthorization is an autogenerated conversion function.
func Convert_v1_OAuthClientAuthorization_To_oauth_OAuthClientAuthorization(in *oauthv1.OAuthClientAuthorization, out *oauth.OAuthClientAuthorization, s conversion.Scope) error {
	return autoConvert_v1_OAuthClientAuthorization_To_oauth_OAuthClientAuthorization(in, out, s)
}

func autoConvert_oauth_OAuthClientAuthorization_To_v1_OAuthClientAuthorization(in *oauth.OAuthClientAuthorization, out *oauthv1.OAuthClientAuthorization, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ClientName = in.ClientName
	out.UserName = in.UserName
	out.UserUID = in.UserUID
	out.Scopes = *(*[]string)(unsafe.Pointer(&in.Scopes))
	return nil
}

// Convert_oauth_OAuthClientAuthorization_To_v1_OAuthClientAuthorization is an autogenerated conversion function.
func Convert_oauth_OAuthClientAuthorization_To_v1_OAuthClientAuthorization(in *oauth.OAuthClientAuthorization, out *oauthv1.OAuthClientAuthorization, s conversion.Scope) error {
	return autoConvert_oauth_OAuthClientAuthorization_To_v1_OAuthClientAuthorization(in, out, s)
}

func autoConvert_v1_OAuthClientAuthorizationList_To_oauth_OAuthClientAuthorizationList(in *oauthv1.OAuthClientAuthorizationList, out *oauth.OAuthClientAuthorizationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]oauth.OAuthClientAuthorization)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_OAuthClientAuthorizationList_To_oauth_OAuthClientAuthorizationList is an autogenerated conversion function.
func Convert_v1_OAuthClientAuthorizationList_To_oauth_OAuthClientAuthorizationList(in *oauthv1.OAuthClientAuthorizationList, out *oauth.OAuthClientAuthorizationList, s conversion.Scope) error {
	return autoConvert_v1_OAuthClientAuthorizationList_To_oauth_OAuthClientAuthorizationList(in, out, s)
}

func autoConvert_oauth_OAuthClientAuthorizationList_To_v1_OAuthClientAuthorizationList(in *oauth.OAuthClientAuthorizationList, out *oauthv1.OAuthClientAuthorizationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]oauthv1.OAuthClientAuthorization)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_oauth_OAuthClientAuthorizationList_To_v1_OAuthClientAuthorizationList is an autogenerated conversion function.
func Convert_oauth_OAuthClientAuthorizationList_To_v1_OAuthClientAuthorizationList(in *oauth.OAuthClientAuthorizationList, out *oauthv1.OAuthClientAuthorizationList, s conversion.Scope) error {
	return autoConvert_oauth_OAuthClientAuthorizationList_To_v1_OAuthClientAuthorizationList(in, out, s)
}

func autoConvert_v1_OAuthClientList_To_oauth_OAuthClientList(in *oauthv1.OAuthClientList, out *oauth.OAuthClientList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]oauth.OAuthClient)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_OAuthClientList_To_oauth_OAuthClientList is an autogenerated conversion function.
func Convert_v1_OAuthClientList_To_oauth_OAuthClientList(in *oauthv1.OAuthClientList, out *oauth.OAuthClientList, s conversion.Scope) error {
	return autoConvert_v1_OAuthClientList_To_oauth_OAuthClientList(in, out, s)
}

func autoConvert_oauth_OAuthClientList_To_v1_OAuthClientList(in *oauth.OAuthClientList, out *oauthv1.OAuthClientList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]oauthv1.OAuthClient)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_oauth_OAuthClientList_To_v1_OAuthClientList is an autogenerated conversion function.
func Convert_oauth_OAuthClientList_To_v1_OAuthClientList(in *oauth.OAuthClientList, out *oauthv1.OAuthClientList, s conversion.Scope) error {
	return autoConvert_oauth_OAuthClientList_To_v1_OAuthClientList(in, out, s)
}

func autoConvert_v1_OAuthRedirectReference_To_oauth_OAuthRedirectReference(in *oauthv1.OAuthRedirectReference, out *oauth.OAuthRedirectReference, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_RedirectReference_To_oauth_RedirectReference(&in.Reference, &out.Reference, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_OAuthRedirectReference_To_oauth_OAuthRedirectReference is an autogenerated conversion function.
func Convert_v1_OAuthRedirectReference_To_oauth_OAuthRedirectReference(in *oauthv1.OAuthRedirectReference, out *oauth.OAuthRedirectReference, s conversion.Scope) error {
	return autoConvert_v1_OAuthRedirectReference_To_oauth_OAuthRedirectReference(in, out, s)
}

func autoConvert_oauth_OAuthRedirectReference_To_v1_OAuthRedirectReference(in *oauth.OAuthRedirectReference, out *oauthv1.OAuthRedirectReference, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_oauth_RedirectReference_To_v1_RedirectReference(&in.Reference, &out.Reference, s); err != nil {
		return err
	}
	return nil
}

// Convert_oauth_OAuthRedirectReference_To_v1_OAuthRedirectReference is an autogenerated conversion function.
func Convert_oauth_OAuthRedirectReference_To_v1_OAuthRedirectReference(in *oauth.OAuthRedirectReference, out *oauthv1.OAuthRedirectReference, s conversion.Scope) error {
	return autoConvert_oauth_OAuthRedirectReference_To_v1_OAuthRedirectReference(in, out, s)
}

func autoConvert_v1_RedirectReference_To_oauth_RedirectReference(in *oauthv1.RedirectReference, out *oauth.RedirectReference, s conversion.Scope) error {
	out.Group = in.Group
	out.Kind = in.Kind
	out.Name = in.Name
	return nil
}

// Convert_v1_RedirectReference_To_oauth_RedirectReference is an autogenerated conversion function.
func Convert_v1_RedirectReference_To_oauth_RedirectReference(in *oauthv1.RedirectReference, out *oauth.RedirectReference, s conversion.Scope) error {
	return autoConvert_v1_RedirectReference_To_oauth_RedirectReference(in, out, s)
}

func autoConvert_oauth_RedirectReference_To_v1_RedirectReference(in *oauth.RedirectReference, out *oauthv1.RedirectReference, s conversion.Scope) error {
	out.Group = in.Group
	out.Kind = in.Kind
	out.Name = in.Name
	return nil
}

// Convert_oauth_RedirectReference_To_v1_RedirectReference is an autogenerated conversion function.
func Convert_oauth_RedirectReference_To_v1_RedirectReference(in *oauth.RedirectReference, out *oauthv1.RedirectReference, s conversion.Scope) error {
	return autoConvert_oauth_RedirectReference_To_v1_RedirectReference(in, out, s)
}

func autoConvert_v1_ScopeRestriction_To_oauth_ScopeRestriction(in *oauthv1.ScopeRestriction, out *oauth.ScopeRestriction, s conversion.Scope) error {
	out.ExactValues = *(*[]string)(unsafe.Pointer(&in.ExactValues))
	out.ClusterRole = (*oauth.ClusterRoleScopeRestriction)(unsafe.Pointer(in.ClusterRole))
	return nil
}

// Convert_v1_ScopeRestriction_To_oauth_ScopeRestriction is an autogenerated conversion function.
func Convert_v1_ScopeRestriction_To_oauth_ScopeRestriction(in *oauthv1.ScopeRestriction, out *oauth.ScopeRestriction, s conversion.Scope) error {
	return autoConvert_v1_ScopeRestriction_To_oauth_ScopeRestriction(in, out, s)
}

func autoConvert_oauth_ScopeRestriction_To_v1_ScopeRestriction(in *oauth.ScopeRestriction, out *oauthv1.ScopeRestriction, s conversion.Scope) error {
	out.ExactValues = *(*[]string)(unsafe.Pointer(&in.ExactValues))
	out.ClusterRole = (*oauthv1.ClusterRoleScopeRestriction)(unsafe.Pointer(in.ClusterRole))
	return nil
}

// Convert_oauth_ScopeRestriction_To_v1_ScopeRestriction is an autogenerated conversion function.
func Convert_oauth_ScopeRestriction_To_v1_ScopeRestriction(in *oauth.ScopeRestriction, out *oauthv1.ScopeRestriction, s conversion.Scope) error {
	return autoConvert_oauth_ScopeRestriction_To_v1_ScopeRestriction(in, out, s)
}

func autoConvert_v1_UserOAuthAccessToken_To_oauth_UserOAuthAccessToken(in *oauthv1.UserOAuthAccessToken, out *oauth.UserOAuthAccessToken, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ClientName = in.ClientName
	out.ExpiresIn = in.ExpiresIn
	out.Scopes = *(*[]string)(unsafe.Pointer(&in.Scopes))
	out.RedirectURI = in.RedirectURI
	out.UserName = in.UserName
	out.UserUID = in.UserUID
	out.AuthorizeToken = in.AuthorizeToken
	out.RefreshToken = in.RefreshToken
	out.InactivityTimeoutSeconds = in.InactivityTimeoutSeconds
	return nil
}

// Convert_v1_UserOAuthAccessToken_To_oauth_UserOAuthAccessToken is an autogenerated conversion function.
func Convert_v1_UserOAuthAccessToken_To_oauth_UserOAuthAccessToken(in *oauthv1.UserOAuthAccessToken, out *oauth.UserOAuthAccessToken, s conversion.Scope) error {
	return autoConvert_v1_UserOAuthAccessToken_To_oauth_UserOAuthAccessToken(in, out, s)
}

func autoConvert_oauth_UserOAuthAccessToken_To_v1_UserOAuthAccessToken(in *oauth.UserOAuthAccessToken, out *oauthv1.UserOAuthAccessToken, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ClientName = in.ClientName
	out.ExpiresIn = in.ExpiresIn
	out.Scopes = *(*[]string)(unsafe.Pointer(&in.Scopes))
	out.RedirectURI = in.RedirectURI
	out.UserName = in.UserName
	out.UserUID = in.UserUID
	out.AuthorizeToken = in.AuthorizeToken
	out.RefreshToken = in.RefreshToken
	out.InactivityTimeoutSeconds = in.InactivityTimeoutSeconds
	return nil
}

// Convert_oauth_UserOAuthAccessToken_To_v1_UserOAuthAccessToken is an autogenerated conversion function.
func Convert_oauth_UserOAuthAccessToken_To_v1_UserOAuthAccessToken(in *oauth.UserOAuthAccessToken, out *oauthv1.UserOAuthAccessToken, s conversion.Scope) error {
	return autoConvert_oauth_UserOAuthAccessToken_To_v1_UserOAuthAccessToken(in, out, s)
}

func autoConvert_v1_UserOAuthAccessTokenList_To_oauth_UserOAuthAccessTokenList(in *oauthv1.UserOAuthAccessTokenList, out *oauth.UserOAuthAccessTokenList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]oauth.UserOAuthAccessToken)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_UserOAuthAccessTokenList_To_oauth_UserOAuthAccessTokenList is an autogenerated conversion function.
func Convert_v1_UserOAuthAccessTokenList_To_oauth_UserOAuthAccessTokenList(in *oauthv1.UserOAuthAccessTokenList, out *oauth.UserOAuthAccessTokenList, s conversion.Scope) error {
	return autoConvert_v1_UserOAuthAccessTokenList_To_oauth_UserOAuthAccessTokenList(in, out, s)
}

func autoConvert_oauth_UserOAuthAccessTokenList_To_v1_UserOAuthAccessTokenList(in *oauth.UserOAuthAccessTokenList, out *oauthv1.UserOAuthAccessTokenList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]oauthv1.UserOAuthAccessToken)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_oauth_UserOAuthAccessTokenList_To_v1_UserOAuthAccessTokenList is an autogenerated conversion function.
func Convert_oauth_UserOAuthAccessTokenList_To_v1_UserOAuthAccessTokenList(in *oauth.UserOAuthAccessTokenList, out *oauthv1.UserOAuthAccessTokenList, s conversion.Scope) error {
	return autoConvert_oauth_UserOAuthAccessTokenList_To_v1_UserOAuthAccessTokenList(in, out, s)
}
