//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1

import (
	oauthv1 "github.com/openshift/api/oauth/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&oauthv1.OAuthAuthorizeToken{}, func(obj interface{}) { SetObjectDefaults_OAuthAuthorizeToken(obj.(*oauthv1.OAuthAuthorizeToken)) })
	scheme.AddTypeDefaultingFunc(&oauthv1.OAuthAuthorizeTokenList{}, func(obj interface{}) {
		SetObjectDefaults_OAuthAuthorizeTokenList(obj.(*oauthv1.OAuthAuthorizeTokenList))
	})
	return nil
}

func SetObjectDefaults_OAuthAuthorizeToken(in *oauthv1.OAuthAuthorizeToken) {
	SetDefaults_OAuthAuthorizeToken(in)
}

func SetObjectDefaults_OAuthAuthorizeTokenList(in *oauthv1.OAuthAuthorizeTokenList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_OAuthAuthorizeToken(a)
	}
}
